name: "demon pipeline CI"
on:
  push:
    branches:
      - main

jobs:
  demo:
    name: "Demo son nom"
    runs-on: ubuntu-latest

    steps:
      - name: "Premiere étape"
        run: echo "Hello world"

      - name: "Script plus complexe"
        run: |
          echo "voici"
          echo "un script"
          echo "plus complexe"
  test:
    runs-on: ubuntu-latest
    steps:
      - name: "Test-step"
        uses: actions/checkout@v4

      - name: "Test-step-2"
        run: echo "Hello world"
